<?xml version="1.0"?>

<robot xmlns:xacro="http://ros.org/wiki/xacro">
	<xacro:property name="M_PI" value="3.14159"/>
	
	<xacro:property name="husky_front_bumper_extend" value="$(optenv HUSKY_FRONT_BUMPER_EXTEND 0)" />
	<xacro:property name="husky_rear_bumper_extend" value="$(optenv HUSKY_REAR_BUMPER_EXTEND 0)" />
	<xacro:arg name="camera_mountpoint" default="sensor_arch_mount_link" />

	<!-- Base Size -->
	<xacro:property name="base_x_size" value="0.98740000" />
	<xacro:property name="base_y_size" value="0.57090000" />
	<xacro:property name="base_z_size" value="0.24750000" />

	<!-- Wheel Mounting Positions -->
	<xacro:property name="wheelbase" value="0.5120" />
	<xacro:property name="track" value="0.5708" />
	<xacro:property name="wheel_vertical_offset" value="0.03282" />

	<!-- Wheel Properties -->
	<xacro:property name="wheel_length" value="0.1143" />
	<xacro:property name="wheel_radius" value="0.1651" />

	<xacro:macro name="husky_base_macro">
	
		<!-- Base link is the center of the robot's bottom plate -->
		<link name="base_link">
			<visual>
			<origin xyz="0 0 0" rpy="0 0 0" />
			<geometry>
				<mesh filename="package://husky_description/meshes/base_link.dae" />
			</geometry>
			</visual>
			<collision>
			<origin xyz="${( husky_front_bumper_extend - husky_rear_bumper_extend ) / 2.0} 0 ${base_z_size/4}" rpy="0 0 0" />
			<geometry>
				<box size="${ base_x_size + husky_front_bumper_extend + husky_rear_bumper_extend } ${base_y_size} ${base_z_size/2}"/>
			</geometry>
			</collision>
			<collision>
			<origin xyz="0 0 ${base_z_size*3/4-0.01}" rpy="0 0 0" />
			<geometry>
				<box size="${base_x_size*4/5} ${base_y_size} ${base_z_size/2-0.02}"/>
			</geometry>
			</collision>
		</link>

		<!-- Base footprint is on the ground under the robot -->
		<link name="base_footprint"/>

		<joint name="base_footprint_joint" type="fixed">
			<origin xyz="0 0 ${wheel_vertical_offset - wheel_radius}" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="base_footprint" />
		</joint>

		<!-- Interial link stores the robot's inertial information -->
		<link name="inertial_link">
			<inertial>
			<mass value="46.034" />
			<origin xyz="-0.00065 -0.085 0.062" />
			<inertia ixx="0.6022" ixy="-0.02364" ixz="-0.1197" iyy="1.7386" iyz="-0.001544" izz="2.0296" />
			</inertial>
		</link>

		<joint name="inertial_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 0 0" />
			<parent link="base_link" />
			<child link="inertial_link" />
		</joint>

		<!-- IMU Link is the standard mounting position for the UM6 IMU.-->
		<!-- Can be modified with environment variables in /etc/ros/setup.bash -->
		<link name="imu_link"/>
		<joint name="imu_joint" type="fixed">
			<origin xyz="$(optenv HUSKY_IMU_XYZ 0.19 0 0.149)" rpy="$(optenv HUSKY_IMU_RPY 0 -1.5708 3.1416)" />
			<parent link="base_link" />
			<child link="imu_link" />
		</joint>
		<gazebo reference="imu_link">
		</gazebo>

		<!-- Husky wheel macros -->
		<xacro:husky_wheel wheel_prefix="front_left">
			<origin xyz="${wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		</xacro:husky_wheel>
		<xacro:husky_wheel wheel_prefix="front_right">
			<origin xyz="${wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		</xacro:husky_wheel>
		<xacro:husky_wheel wheel_prefix="rear_left">
			<origin xyz="${-wheelbase/2} ${track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		</xacro:husky_wheel>
		<xacro:husky_wheel wheel_prefix="rear_right">
			<origin xyz="${-wheelbase/2} ${-track/2} ${wheel_vertical_offset}" rpy="0 0 0" />
		</xacro:husky_wheel>

		<!-- Husky decorations -->
		<xacro:husky_decorate />

		<!-- Husky camera sensor parent link -->
		<xacro:sensor_arch prefix="" parent="top_plate_link">
			<origin xyz="-0.35 0 0.51" rpy="0 0 -${M_PI}"/>  <!-- xyz="-0.18 0 0.51" -->
		</xacro:sensor_arch>
		
		<!-- For camera without inbuilt link and joint in xacro -->
		<!-- <link name="camera_link"/> # to be used as mount-point
		<joint name="camera_joint" type="fixed">
			<origin xyz="0 0 0" rpy="0 -${M_PI/2} 0" />
			<parent link="$(arg camera_mountpoint)"/>
			<child link="camera_link" />
		</joint>
		<xacro:include filename="$(find husky_description)/urdf/accessories/intel_realsense.urdf.xacro"/>
		<xacro:intel_realsense_mount prefix="camera" topic="realsense" parent_link="camera_link"/> -->

		<!-- For camera with inbuilt link and joint in xacro -->
		<!-- <xacro:include filename="$(find husky_3d_slam)/description/urdf/accessories/kinect_camera.urdf.xacro"/>
		<xacro:kinect_camera name="kinect_camera" parent="$(arg camera_mountpoint)"> # moint-point is arg:camera_mountpoint
			<origin xyz="$(arg kinect_xyz)" rpy="$(arg kinect_rpy)"/>
		</xacro:kinect_camera>
		-->

		<!-- Husky gazebo plugins -->
		<gazebo>
			<plugin name="gazebo_ros_control" filename="libgazebo_ros_control.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
			<legacyModeNS>true</legacyModeNS>
			</plugin>
		</gazebo>

		<gazebo>
			<plugin name="imu_controller" filename="libhector_gazebo_ros_imu.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
			<updateRate>50.0</updateRate>
			<bodyName>base_link</bodyName>
			<topicName>imu/data</topicName>
			<accelDrift>0.005 0.005 0.005</accelDrift>
			<accelGaussianNoise>0.005 0.005 0.005</accelGaussianNoise>
			<rateDrift>0.005 0.005 0.005 </rateDrift>
			<rateGaussianNoise>0.005 0.005 0.005 </rateGaussianNoise>
			<headingDrift>0.005</headingDrift>
			<headingGaussianNoise>0.005</headingGaussianNoise>
			</plugin>
		</gazebo>

		<gazebo>
			<plugin name="gps_controller" filename="libhector_gazebo_ros_gps.so">
			<robotNamespace>$(arg robot_namespace)</robotNamespace>
			<updateRate>40</updateRate>
			<bodyName>base_link</bodyName>
			<frameId>base_link</frameId>
			<topicName>navsat/fix</topicName>
			<velocityTopicName>navsat/vel</velocityTopicName>
			<referenceLatitude>49.9</referenceLatitude>
			<referenceLongitude>8.9</referenceLongitude>
			<referenceHeading>0</referenceHeading>
			<referenceAltitude>0</referenceAltitude>
			<drift>0.0001 0.0001 0.0001</drift>
			</plugin>
		</gazebo>

		<!-- Optional custom includes. ->
		<xacro:include filename="$(arg urdf_extras)" /> -->

	</xacro:macro>
</robot>
